"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const ExpressAdapter_1 = __importDefault(require("../../adapter/ExpressAdapter"));
const ProfissionalController_1 = __importDefault(require("../../controller/ProfissionalController"));
const ProfissaoController_1 = __importDefault(require("../../controller/ProfissaoController"));
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.get("/profissional/", ExpressAdapter_1.default.create(ProfissionalController_1.default.get));
app.post("/profissional/", ExpressAdapter_1.default.create(ProfissionalController_1.default.create));
app.delete("/profissional/:id", ExpressAdapter_1.default.create(ProfissionalController_1.default.delete));
app.get("/profissao/", ExpressAdapter_1.default.create(ProfissaoController_1.default.get));
app.post("/profissao/", ExpressAdapter_1.default.create(ProfissaoController_1.default.create));
// app.get("/:id", ExpressAdapter.create(ProfissionalController.getById));
app.listen(3000, '0.0.0.0', () => console.log(`Listening on port:  3000 - PRD VERSÃO 2`));
