version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./api/postgres:/var/lib/postgresql/data 
    networks:
      - paciente360-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ruan.oliveira@paciente360.health"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - paciente360-network
  api:
    image: api/.
 
networks: 
  paciente360-network:
    driver: bridge